### ISSUE TITLE
No invalid example

### ISSUE THREAD

**Issue by JoshuaShaffer1** [go-vela/docs-old#29]
It would be helpful to have an example of Vela's response with an incorrect validation file; only a valid response is listed currently
https://go-vela.github.io/docs/usage/reference/cli/validate/#sample

**Comment by kneal** [comment]
@JoshuaShaffer1 Providing an invalid example is not something we do other CLI command docs. Do you have a use case for why that information would be valuable?

**Comment by JoshuaShaffer1** [comment]
@kneal an invalid example would help clarify that this command is running YAML validation only. 

Based on the phrases
> ...run validate to ensure your pipeline is runnable 

> Use this command to validate your **_pipeline_**

I thought there was more involved validation going on behind the scenes, which isn't the case (unless I'm mistaken!)

Clarification on this doc page of what `validate` is doing would be a great way to remedy this if you don't want to add an invalid example.

**Comment by kneal** [comment]
That's great feedback! Yeah, the idea of the command was to allow users to run the same compile process locally we run on the Yaml when it's pushed to GitHub. 

I'm kinda leaning towards your idea about clarification in the documentation around what it's doing. Mostly, because when you run the command if it fails it doesn't really say "invalid yaml" or anything. Just gives what is invalid about that Yaml. So, documenting a ton of different ways could be tricky.

**Comment by JoshuaShaffer1** [comment]
That makes sense; documenting all those error scenarios would be unnecessary, I agree 😊👍
